# Generated by Django 6.0.3 on 2026-03-26 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_discount_price_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_l',
            field=models.BooleanField(default=True, verbose_name='Large Available'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_m',
            field=models.BooleanField(default=True, verbose_name='Medium Available'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_s',
            field=models.BooleanField(default=True, verbose_name='Small Available'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_xl',
            field=models.BooleanField(default=False, verbose_name='XL Available'),
        ),
    ]
