# Generated by Django 6.0.3 on 2026-03-31 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_brandsetting_contactmessage_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandSetting',
        ),
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='HomeSlider',
        ),
        migrations.DeleteModel(
            name='Newsletter',
        ),
        migrations.DeleteModel(
            name='ProductColor',
        ),
    ]
